name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Start DBus Service
      run: |
        sudo service dbus start  
        
    - name: Build the Docker image
      run: docker build -t sharath1036/rejoicehub:latest .
    - name: Push to Dockerhub
      run: docker push sharath1036/rejoicehub:latest
